"use client";

import { useEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";

/**
 * The phone stand-in for "Take it for a spin": the desktop demo is a desktop window and
 * never loads below `md`, so phones get four stills of it to swipe through instead — the
 * same story the demo's autoplay tour tells (`app-demo/demo-tour.ts`).
 *
 * Swiping is native scroll-snap; the only script is the dots, which follow the slide in
 * view and jump to one when tapped. The stills (`public/waitlist/tour/`, regenerated by
 * `scripts/dev/capture-waitlist-tour.mjs`) are requested only once the strip is within
 * 600px of the screen — and never on desktop, where it is `display: none` and so never
 * intersects. Not `loading="lazy"` alone: Chrome's lazy margin runs to ~2,500px, which
 * fetched them at page load, three screens early.
 */
const SLIDES = [
  {
    name: "suggestion",
    caption: "Maya has gone quiet — and you said you'd check in monthly.",
    alt: "A suggestion to reach out to Maya Okafor, marked dormant, last touched 46 days ago.",
  },
  {
    name: "timeline",
    caption: "Everything about her in one place: email, meetings, LinkedIn.",
    alt: "Maya's timeline: an email, a coffee meeting, a LinkedIn message and a call.",
  },
  {
    name: "draft",
    caption: "It remembers what you promised, and drafts the follow-up.",
    alt: "An answer recalling the deck promised to Maya, with a drafted email ready to send.",
  },
  {
    name: "constellation",
    caption: "And you can always see where everyone sits.",
    alt: "A star chart of the network, with Maya's card open beside the Figma constellation.",
  },
] as const;

export function DemoPeek() {
  const stripRef = useRef<HTMLDivElement>(null);
  const [active, setActive] = useState(0);
  const [near, setNear] = useState(false);

  useEffect(() => {
    const strip = stripRef.current;
    if (!strip) return;
    const io = new IntersectionObserver(
      (entries) => {
        if (!entries.some((e) => e.isIntersecting)) return;
        setNear(true);
        io.disconnect();
      },
      { rootMargin: "600px 0px" }
    );
    io.observe(strip);
    return () => io.disconnect();
  }, []);

  useEffect(() => {
    const strip = stripRef.current;
    if (!strip) return;
    const io = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) setActive(Number((e.target as HTMLElement).dataset.index));
        }
      },
      { root: strip, threshold: 0.6 }
    );
    for (const slide of strip.children) io.observe(slide);
    return () => io.disconnect();
  }, []);

  function go(i: number) {
    const slide = stripRef.current?.children[i] as HTMLElement | undefined;
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    slide?.scrollIntoView({ behavior: reduced ? "auto" : "smooth", block: "nearest", inline: "center" });
  }

  return (
    <div>
      <div
        ref={stripRef}
        role="region"
        aria-roledescription="carousel"
        aria-label="Screens from the preview"
        tabIndex={0}
        className="-mx-6 flex snap-x snap-mandatory gap-4 overflow-x-auto px-6 pb-2 [scrollbar-width:none] focus-visible:outline-none [&::-webkit-scrollbar]:hidden"
      >
        {SLIDES.map((s, i) => (
          <figure
            key={s.name}
            data-index={i}
            aria-roledescription="slide"
            aria-label={`${i + 1} of ${SLIDES.length}`}
            className="w-[84%] max-w-[420px] shrink-0 snap-center"
          >
            <div className="overflow-hidden rounded-2xl border border-[#e8f3f1]/10 bg-[#0e1524] shadow-[0_24px_60px_-24px_rgba(0,0,0,0.8)]">
              {/* Cut from the desktop window, so the right and bottom edges fade rather
                  than stop mid-word. */}
              {near ? (
                <>
                  {/* eslint-disable-next-line @next/next/no-img-element -- pre-sized WebP pair
                      with its own srcset; nothing left for the optimizer to do. */}
                  <img
                    src={`/waitlist/tour/${s.name}-420.webp`}
                    srcSet={`/waitlist/tour/${s.name}-420.webp 420w, /waitlist/tour/${s.name}-840.webp 840w`}
                    sizes="(max-width: 500px) 84vw, 420px"
                    width={420}
                    height={315}
                    loading="lazy"
                    decoding="async"
                    draggable={false}
                    alt={s.alt}
                    className="block h-auto w-full select-none [mask-image:linear-gradient(to_right,black_82%,transparent),linear-gradient(to_bottom,black_85%,transparent)] [mask-composite:intersect]"
                  />
                </>
              ) : (
                <div aria-hidden="true" className="aspect-[4/3] w-full" />
              )}
            </div>
            <figcaption className="mt-3 px-1 text-sm leading-relaxed text-[#9aada8]">{s.caption}</figcaption>
          </figure>
        ))}
      </div>

      <div className="mt-4 flex justify-center gap-2">
        {SLIDES.map((s, i) => (
          <button
            key={s.name}
            type="button"
            onClick={() => go(i)}
            aria-label={`Show screen ${i + 1} of ${SLIDES.length}`}
            aria-current={active === i ? "true" : undefined}
            className="flex size-6 items-center justify-center"
          >
            <span
              className={cn(
                "block h-1.5 rounded-full transition-[width,background-color] duration-300",
                active === i ? "w-5 bg-[#f2c14e]" : "w-1.5 bg-[#e8f3f1]/25"
              )}
            />
          </button>
        ))}
      </div>
    </div>
  );
}
